name: garden_vision
description: Simple camera demo
publish_to: "none"
version: 1.0.0+1  # build name (1.0.0) + build number (1)

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  
  # UI Libraries
  velocity_x: ^4.1.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  forui: ^0.7.0
  http: ^1.5.0
  image_picker: ^1.2.0

  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  camera: ^0.11.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
