// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJtfvQLlt_GRbnQRkiCDQaNe_R1SN9yY4',
    appId: '1:695245610759:web:a5376fee58e604f6522fa2',
    messagingSenderId: '695245610759',
    projectId: 'wecooked-sase2025',
    authDomain: 'wecooked-sase2025.firebaseapp.com',
    databaseURL: 'https://wecooked-sase2025-default-rtdb.firebaseio.com',
    storageBucket: 'wecooked-sase2025.firebasestorage.app',
    measurementId: 'G-VF1282Y2JV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-bCOMqI_3F6w91AIrl6Y9GZ9Ulw28rAA',
    appId: '1:695245610759:android:5ccaa4cebe0fac20522fa2',
    messagingSenderId: '695245610759',
    projectId: 'wecooked-sase2025',
    databaseURL: 'https://wecooked-sase2025-default-rtdb.firebaseio.com',
    storageBucket: 'wecooked-sase2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ9xAXW4GQU40YaAnC9ohb2SjMhc8LZ9A',
    appId: '1:695245610759:ios:61a28475baeab193522fa2',
    messagingSenderId: '695245610759',
    projectId: 'wecooked-sase2025',
    databaseURL: 'https://wecooked-sase2025-default-rtdb.firebaseio.com',
    storageBucket: 'wecooked-sase2025.firebasestorage.app',
    iosBundleId: 'com.example.wecookedsase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ9xAXW4GQU40YaAnC9ohb2SjMhc8LZ9A',
    appId: '1:695245610759:ios:61a28475baeab193522fa2',
    messagingSenderId: '695245610759',
    projectId: 'wecooked-sase2025',
    databaseURL: 'https://wecooked-sase2025-default-rtdb.firebaseio.com',
    storageBucket: 'wecooked-sase2025.firebasestorage.app',
    iosBundleId: 'com.example.wecookedsase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJtfvQLlt_GRbnQRkiCDQaNe_R1SN9yY4',
    appId: '1:695245610759:web:8b1927c64e37c2c2522fa2',
    messagingSenderId: '695245610759',
    projectId: 'wecooked-sase2025',
    authDomain: 'wecooked-sase2025.firebaseapp.com',
    databaseURL: 'https://wecooked-sase2025-default-rtdb.firebaseio.com',
    storageBucket: 'wecooked-sase2025.firebasestorage.app',
    measurementId: 'G-3JSQGZTTR4',
  );

}